### ISSUE TITLE
Separate front and back roadmap

### ISSUE THREAD

**Issue by Nanquitas** [formation-dwwm/DWWM_Playground#23]

**Comment by kukvs666** [comment]
- [x] Faire le système de toggle
- [x] séparer le template en deux. 
- [x] faire le mapping sur les deux images
