### ISSUE TITLE
Create the wordpress theme

### ISSUE THREAD

**Issue by Nanquitas** [formation-dwwm/DWWM_Playground#3]
- [x] Select a base theme and create a child of it
- [x] Update the graphical charts to match our mock-up
- [x] Coherent with ionic app theme

**Comment by kital-dwwp** [comment]
# title
**fdf**
- [ ] fdf

**Comment by Cursusdev** [comment]
Rajouter dans le thème enfants :
- [x] fichiers php: index, header, footer, sidebar, style.css ...
- [x] mettre en place de fichier template du thème

**Comment by Cursusdev** [comment]
Mettre sur Github le thème enfants/parent
- [x] faire le script de mise à jour automatique

**Comment by Cursusdev** [comment]
Réaliser la page d'accueil :
- [x] Modifier le header suivant la maquette
- [x] Modifier le post du thème pour avoir l'image à gauche
- [x] Réaliser le style css responsive

**Comment by Cursusdev** [comment]
Page d'accueil 
- [x] fusionner le header et le content-article
- [x] faire un état des fonctionnalités wordpress

**Comment by Cursusdev** [comment]
Les modifications des articles sont dans le fichier content-article.php.
Les pages sont bloqués sur la page d'accueil depuis les fichiers content-home et archive-blog.php
La suite :
- [ ] Réaliser la page accueil + roadmap
- [ ] Rajouter l'extension du Forum
- [ ] Établir les liens entre les pages accueil / accueil+roadmap / forum
